[build]
builder = "NIXPACKS"
buildCommand = "npm ci --only=production"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
